name: CI
on:
  pull_request:
    branches:
      - '*'
  push:
    branches:
      - master
jobs:
  format:
    name: Format
    runs-on: ubuntu-20.04
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Check with Scalafmt
        run: sbt ++2.12.12 fmtCheck
  build:
    name: Test (${{ matrix.scala }}, ${{ matrix.java }})
    needs: format
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        scala:
          - 2.12.12
        java:
          - adopt@1.11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Test (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} clean test
  scripted:
    name: Scripted (${{ matrix.scala }}, ${{ matrix.java }})
    needs: format
    strategy:
      matrix:
        os:
          - ubuntu-20.04
        scala:
          - 2.12.12
        java:
          - adopt@1.11
    runs-on: ${{ matrix.os }}
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: ${{ matrix.java }}
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Scripted (${{ matrix.scala }}, ${{ matrix.java }})
        run: sbt ++${{ matrix.scala }} core/publishLocal scripted
        env:
          STEP: "scripted"
  publish_212:
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    name: Publish Snapshot 2.12
    needs: [ build, scripted ]
    runs-on: ubuntu-20.04
    steps:
      - name: Branch Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Install Java And Sbt
        uses: olafurpg/setup-scala@v10
        with:
          java-version: adopt@1.11
      - name: Cache
        uses: actions/cache@v2
        with:
          path: |
            $HOME/.cache/coursier
            $HOME/.ivy2/cache
            $HOME/.sbt/boot/
            $HOME/.sbt
            lib_managed
            target
            project/target
          key: ${{ runner.os }}-cache-v2-${{ hashFiles('**/*.sbt') }}-${{ hashFiles('project/build.properties') }}
      - name: Publish Snapshot for Scala 2.12
        run: CI_SNAPSHOT_RELEASE=publish sbt ++2.12.12 releaseIt
        env:
          PGP_PASSPHRASE: ${{ secrets.PGP_PASSPHRASE }}
          PGP_SECRET: ${{ secrets.PGP_SECRET }}
          SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
          SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
